name-template: Draft YYYYMMDDリリース # 次バージョンのタグ名をタイトルに設定
tag-template: "v$NEXT_PATCH_VERSION" # 次バージョンのタグ名を設定
change-template: "- $TITLE (#$NUMBER) @$AUTHOR" # PR情報のテンプレート
template: | # リリースの内容テンプレート
  # hogehoge v$NEXT_PATCH_VERSION リリースノート
  ## 新規追加
  - XXX追加（yyyy）
  - 追加がない場合は「なし」とする

  ## Changes
  $CHANGES
